application: mealpha011a
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /models
  static_dir: models

- url: /textures
  static_dir: textures

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /docs
  static_dir: docs
  
- url: /examples
  static_dir: examples  

- url: /404.html
  static_files: 404.html
  upload: 404.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /chris.*
  script: chris.app

- url: /eden.*
  script: EdenEden.app
  
- url: /cic.*
  script: EdenCIC.app
    
- url: /.*
  script: main.app

inbound_services:
- channel_presence


libraries:
- name: jinja2
  version: latest